Space Travellors' Hub
DilsherB/Space-Travelers-Hub pull request #53
Opened 2023-06-22 16:57 UTC by DilsherB

In this project we @DilsherB and @Mahamadou-Nouridine did the following:
1. created react app
2. install dependencies
3. created `routs` and `views`
4. NavBar created and `NavLink` applied
5. fetch data from API
6. show data in a proper format on pages `Rockets` and `Missions`
7. Actions and reducers written for both `Rockets` and `Missions`
8. `Reserve` and `Cancel Reserve` functionality applied for `Rockets`
9. `Join Mission` and `Leave Mission` functionality applied for `Missions`
10. conditional rendering applied
11. `My Profie` section created which shows `Reserved Rockets` and `Joined Missions`
12. Readme updated

2023-06-22 17:48 UTC, TadesseDev requested changes
### Hi Team

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
 - [x] Good job overall following the template design ✅
 - [x]  Correct GitFlow  ✅
 - [x]  Good commit history  ✅
 - [x]  Good PR title/description  ✅
 - [x]  All linters passed  ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 17:48 UTC, TadesseDev commented on src/index.js
> +  </React.StrictMode>
- [ ] Dear Team, Please keep in mind for this milestone you are expected to write unit tests with React Testing Library and Jest (for unit tests). Testing is one major part of this day's development and provides an assertion over your overall project. Please add tests using the `React Testing Library and Jest`

2023-06-22 17:48 UTC, TadesseDev commented on src/App.jsx
> +  )
- [ ] It's great that you have a blue text on the active page team ✅. But It's a common practice and provides an advantage when it comes to UX to indicate an active page with underlined text. Please add an underline on the active page.

![image](https://github.com/DilsherB/Space-Travelers-Hub/assets/69077061/233b4636-1afc-4403-b0ca-0614b642ad55)

2023-06-23 00:27 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi team, 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done adding tests and updating the style for the active link. ✔
- You successfully completed all the requirements.  🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 02:15 UTC, merged